import type { Metadata } from "next";
import { Roboto } from 'next/font/google'
 
import StoreProvider from "./StoreProvider";

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "MobiAuto",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
        <body className={roboto.className} style={{backgroundColor: '#F9F6FC'}}>{children}</body>
      </StoreProvider>
    </html>
  );
}
